server:
  port: 2718


#thymeleaf start
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:templates/
    suffix: .html


  datasource:
    url: jdbc:sqlite:ticket.db
    name: ticket
    driver-class-name: org.sqlite.JDBC
mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: org.spring.springboot.domain



#thymeleaf end